language: scala

sudo: false

services:
   - docker
scala:
   - 2.11.7
jdk:
   - oraclejdk8

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/launchers/0.13.9/
  - $HOME/.sbt/boot/

script:
  - "cp .sbtignore $HOME/.sbtignore && cat $HOME/.sbtignore"
  - "sbt test"
  - "project/bin/run-travis"

